import Head from "next/head";
import { useTranslation } from "react-i18next";

const SocialNetwork = () => {
    const { t } = useTranslation();
    
    return (
        <div className="">
            <Head>
                <title>{t("navbar.reports")} | ArmourWeb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/awLogo-nobg.png" />
            </Head>
            REPORTE DE REDES SOCIALES
        </div>
    )
}

export default SocialNetwork;