import Header from "@/components/Header/index.js";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { useTranslation } from "react-i18next";

const AdminWebPages = () => {
    const { t } = useTranslation();
    return (
        <div className="">
            <Head>
                <title>{t("navbar.reports")} | ArmourWeb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/awLogo.png" />
            </Head>
            REPORTE DE PAGINAS WEB ADMIN
        </div>
    )
}

export default AdminWebPages;