import FirstStep from '@/components/ManagePageBuilder/firstStep';
import Navbar from '@/components/ManagePageBuilder/navbar';
import PersonalizationHeader from '@/components/ManagePageBuilder/personalizationHeader';
import Sidebar from '@/components/ManagePageBuilder/sidebar';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

export default function ManagePageBuilder() {
    const { t } = useTranslation();
    const [showFirstStep, setShowFirstStep] = useState(true);

    const [navbarPosition, setNavbarPosition] = useState("top"); // Cambia esta variable según tu preferencia ("left", "top", "right")

    useEffect(() => {
        const handleNavbarPositionChange = (event) => {
            const selectedOption = event.option;
            setNavbarPosition(selectedOption);
        };

        window.addEventListener("navbarPositionChange", handleNavbarPositionChange);

        return () => {
            // Limpia el event listener cuando el componente se desmonta
            window.removeEventListener("navbarPositionChange", handleNavbarPositionChange);
        };
    }, []); // Asegura que el event listener se configure solo una vez

    return (
        <>
            <Head>
                <title>{t("page-builder.new-page")} | ArmourWeb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/awLogo-nobg.png" />
            </Head>
            <div className="bg-black h-screen w-screen flex">
                {showFirstStep && <FirstStep setShowFirstStep={setShowFirstStep} />}
                <Sidebar />
                <div className="w-[75%] h-screen">
                    <PersonalizationHeader />
                    <div className="m-4 w-auto h-[calc(100vh-7rem)] shadow-md bg-white relative">
                        <Navbar position={navbarPosition} >
                            <div>
                                NUEVA SECCION
                            </div>
                        </Navbar>
                        {/* Contenido adicional de la página aquí */}
                    </div>
                </div>
            </div>
        </>
    );
}
