import PersonalizationHeader from '@/components/ManagePageBuilder/personalizationHeader';
import Sidebar from '@/components/ManagePageBuilder/sidebar';
import Head from 'next/head';
import React from 'react'
import { useTranslation } from 'react-i18next';

export default function ManagePageBuilder() {
    const { t } = useTranslation();
    return (
        <>
            <Head>
                <title>{t("page-builder.new-page")} | ArmourWeb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/awLogo-nobg.png" />
            </Head>
            <div className='bg-black h-full w-full flex'>
                <Sidebar />
                <div className='w-[75%] h-full'>
                    <PersonalizationHeader />
                    <div className='m-4 w-auto h-[calc(100vh-7rem)] shadow-md bg-white'></div>
                </div>
            </div>
        </>
    )
}