
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useTranslation } from "react-i18next";

const EditProfile = () => {
    const { t } = useTranslation();
    const [formData, setFormData] = useState({
        name: '',
        lastname: '',
        phone: '',
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value,
        });
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        // Aquí puedes enviar los datos actualizados al servidor o realizar otras acciones necesarias.
    };

    return (
        <>
            <Head>
                <title>{t("navbar.editProfile")} | ArmourWeb</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/awLogo.png" />
            </Head>
            <form onSubmit={handleSubmit} className="bg-main h-[92vh] px-20 py-20">
                <div className="flex items-center mx-auto italic rounded-[.5rem] border border-2 border-black w-[24rem] h-[6rem] justify-center">
                    <p className="m-0 font-bold text-[4rem]">{t('navbar.my-profile')}</p>
                </div>

                <div className="w-[60%] mx-auto mt-20">
                    <p className="text-[1.8rem] font-bold mb-4">{t('user-data.basic-info')}</p>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="name" className="text-[1.5rem] font-semibold">
                            {t('user-data.name')}:
                        </label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            value={formData.name}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="lastname" className="text-[1.5rem] font-semibold">
                            {t('user-data.lastname')}:
                        </label>
                        <input
                            type="text"
                            id="lastname"
                            name="lastname"
                            value={formData.lastname}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="phone" className="text-[1.5rem] font-semibold">
                            {t('user-data.phone')}:
                        </label>
                        <input
                            type="text"
                            id="phone"
                            name="phone"
                            value={formData.phone}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>

                    <p className="text-[1.8rem] font-bold mt-10 mb-4">{t("user-data.social-network")}</p>

                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="phone" className="text-[1.5rem] font-semibold">
                            {t('user-data.fb')}:
                        </label>
                        <input
                            type="text"
                            id="facebook"
                            name="facebook"
                            value={formData.facebook}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="phone" className="text-[1.5rem] font-semibold">
                            {t('user-data.twitter')}:
                        </label>
                        <input
                            type="text"
                            id="twitter"
                            name="twitter"
                            value={formData.twitter}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="phone" className="text-[1.5rem] font-semibold">
                            {t('user-data.linked-in')}:
                        </label>
                        <input
                            type="text"
                            id="linkedin"
                            name="linkedin"
                            value={formData.linkedin}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                    <div className="flex items-center justify-between my-2">
                        <label htmlFor="phone" className="text-[1.5rem] font-semibold">
                            {t('user-data.web-page')}:
                        </label>
                        <input
                            type="text"
                            id="webpage"
                            name="webpage"
                            value={formData.webpage}
                            onChange={handleChange}
                            className="text-[1.5rem] font-semibold bg-transparent border border-3 border-gray-800 rounded-xl text-black px-4"
                        />
                    </div>
                </div>
                <div className="flex w-[35%] mx-auto mt-10">
                    <div className="mx-auto cursor-pointer relative flex items-center justify-center w-[8rem] bg-red-900 border border-2 border-gray-300 hover:bg-red-700 text-[1.4rem] text-center mt-3 py-2 px-4 rounded-xl text-gray-200">
                        <Link href={"/myProfile"}>
                            <button className="flex items-center">
                                {t('buttons.cancel')}
                                {/* <img className="w-[1rem] ml-2" src="./svgs/edit.svg" alt="Edit Icon" /> */}
                            </button>
                        </Link>
                    </div>
                    <div className="mx-auto cursor-pointer relative flex items-center justify-center w-[8rem] bg-green-900 border border-2 border-gray-300 hover:bg-green-700 text-[1.4rem] text-center mt-3 py-2 px-4 rounded-xl text-gray-200">
                        <button type="submit" className="flex items-center">
                            {t('buttons.confirm')}
                            {/* <img className="w-[1rem] ml-2" src="./svgs/edit.svg" alt="Edit Icon" /> */}
                        </button>
                    </div>
                </div>
            </form>
        </>
    );
}

export default EditProfile;